plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tipster.pro3'
    compileSdk 35

    defaultConfig {
        applicationId "com.tipster.pro3"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
